version: '3.7'

services:

  react:
    container_name: memewars-react${CONTAINERS_SUFFIX}
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./:/app/
