version: '3.7'

services:

  django:
    container_name: memewars-django${CONTAINERS_SUFFIX}
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file:
      - .env
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - postgres
    volumes:
      - ./api/src:/app/src/
      - ./api/scripts/entrypoint.sh:/app/scripts/entrypoint.sh
      - ./api/scripts/check_project.sh:/app/scripts/check_project.sh
      - ./api/requirements:/app/requirements/

  postgres:
    container_name: memewars-postgres${CONTAINERS_SUFFIX}
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - memewars-postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: memewars-pgadmin${CONTAINERS_SUFFIX}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    volumes:
      - memewars-pgadmin-data:/var/lib/pgadmin

  react:
    container_name: memewars-react${CONTAINERS_SUFFIX}
    build:
      context: .
      dockerfile: ./app/Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./app/src:/app/src
      - ./app/scripts/entrypoint.sh:/app/scripts/entrypoint.sh

volumes:
  memewars-postgres-data:
  memewars-pgadmin-data:
