# Adopted from https://github.com/mikepenz/release-changelog-builder-action

name: 'Create release'
on:
  push:
    tags:
      - '*'
jobs:
  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    name: 'Create a new release from a tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: '.github/workflows/changelog-configuration.json'
      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03
        with:
          body: ${{ steps.github_release.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
